<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.kcharkseliani.kafka.connect.websocket</groupId>
  <artifactId>kafka-websocket-source-connector</artifactId>
  <packaging>jar</packaging>
  <version>local-dev</version>
  <name>kafka-websocket-source-connector</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <!-- Kafka Connect and Kafka Clients -->
    <dependency>
        <groupId>org.apache.kafka</groupId>
        <artifactId>connect-api</artifactId>
        <version>3.8.0</version>
        <scope>provided</scope>
    </dependency>
    <dependency>
        <groupId>org.apache.kafka</groupId>
        <artifactId>kafka-clients</artifactId>
        <version>3.8.0</version>
        <scope>provided</scope>
    </dependency>

    <!-- Java-WebSocket Library -->
    <dependency>
        <groupId>org.java-websocket</groupId>
        <artifactId>Java-WebSocket</artifactId>
        <version>1.5.2</version>
    </dependency>
    
      <!-- JUnit 5 -->
    <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-engine</artifactId>
        <version>5.9.2</version> <!-- Make sure this version matches the one you need -->
        <scope>test</scope>
    </dependency>

    <!-- Mockito Core -->
    <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>5.14.0</version> <!-- Update this version as needed -->
        <scope>test</scope>
    </dependency>

    <!-- Mockito JUnit Jupiter Extension for JUnit 5 -->
    <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-junit-jupiter</artifactId>
        <version>5.14.0</version>
        <scope>test</scope>
    </dependency>

    <!-- For setting up Testcontainers with Kafka and Kafka Connect -->
    <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>kafka</artifactId>
        <version>1.19.1</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>org.testcontainers</groupId>
        <artifactId>junit-jupiter</artifactId>
        <version>1.19.1</version>
        <scope>test</scope>
    </dependency>

    <!-- For making REST requests to Connect -->
    <dependency>
        <groupId>org.apache.httpcomponents.client5</groupId>
        <artifactId>httpclient5</artifactId>
        <version>5.2</version>
        <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <resources>
        <!-- For adding config.properties file with resource filtering to replace placeholders-->
        <resource>
            <directory>src/main/resources</directory>
            <filtering>true</filtering>
        </resource>
    </resources> 
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.6.0</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <!-- <configuration>
              <relocations>
                <relocation>
                  <pattern>org.apache.kafka</pattern>
                  <shadedPattern>shaded.org.apache.kafka</shadedPattern>
                </relocation>
              </relocations>
            </configuration> -->
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.5.3</version>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>3.5.3</version>
        <executions>
          <execution>
            <goals>
              <!-- Executes integration tests that match patterns like *IT.java -->
              <goal>integration-test</goal>
              <!-- Checks the results of the integration test phase -->
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <source>17</source>
          <target>17</target>
        </configuration>
      </plugin>
      <!-- Add Antrun plugin to move shaded JAR only into the target/plugins 
      folder for integration tests with Testcontainers -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>copy-shaded-jar</id>
            <phase>package</phase>
            <configuration>
              <target>
                <mkdir dir="target/plugins"/>
                <copy todir="target/plugins" flatten="true">
                  <fileset dir="target">
                    <include name="kafka-websocket-source-connector-*.jar"/>
                    <exclude name="original-*.jar"/>
                  </fileset>
                </copy>
              </target>
            </configuration>
            <goals>
              <goal>run</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins> 
  </build>
</project>

