name: Create Release on Merge to Dev

on:
  push:
    branches:
      - dev
      # This is temporary to allow workflow testing
      - feature/2-add-dev-release-workflow

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v3

    # Step 2: Set up Java and Maven
    - name: Set up JDK 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'
        distribution: 'adopt'
        cache: 'maven'

    # Step 3: Install GitVersion
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.3
      with:
        versionSpec: '6.x'

    # Step 4: Run GitVersion to determine the version
    - name: Determine version with GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.0.3

    # Step 5: Update Maven POM version
    - name: Display Version
      run: echo "Version ${{ steps.gitversion.outputs.semVer }}"

    - name: Set Maven Project Version
      run: mvn versions:set -DnewVersion=${{ steps.gitversion.outputs.semVer }}

    # Step 6: Build the project
    - name: Build the project
      run: mvn clean package

    # Step 7: Upload build artifact as a release
    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.semVer }}
        release_name: Release ${{ steps.gitversion.outputs.semVer }}
        draft: true
        prerelease: true

    - name: Upload .jar to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/kafka-websocket-source-connector-${{ steps.gitversion.outputs.semVer }}.jar
        # asset_name: kafka-websocket-source-connector-${{ steps.gitversion.outputs.semVer }}.jar
        asset_content_type: application/java-archive
